---
title: "GGplot"
name: Arden Moser
output: html_document
---
# Load Tidyverse
```{r}
library(tidyverse)
```

# Import data file
```{r}
height_data <- read.csv("height_data_clean.csv") # Import file
summary(height_data) # View structure, contents, and dimensions of data file
```

# Plot raw data
```{r}
height_data %>% 
  select(height_cm, survey_date, pop) %>% # Select only heights, survey dates, and population ids
  ggplot(aes(x = survey_date,
             y = height_cm,
             color = pop,
             group = pop,
             shape = pop)) +
  geom_point() + # Plot line graph
  geom_smooth(method = "lm") + # Plot Regression line
  theme(axis.text.x = element_text(angle = 90)) + # Orient x-axis labels for clarity
  labs( # add titles for clarity
    title = "Heights per Population Over Time",
    x = "Survey Date (Year-Month-Day)",
    y = "Height (cm)"
  )
```

# Plot January 27, 2023 Subset
```{r}
height_data %>% 
  select(height_cm, pop) %>% # Select only heights, survey dates, and population ids
  ggplot(aes(x = pop,
             y = height_cm,
             color = pop,
             group = pop)) +
  geom_boxplot() + # Plot boxplot
  theme(axis.text.x = element_text(angle = 90)) + # Orient x-axis labels for clarity
  labs( # add titles for clarity
    title = "Height per Population in January 27, 2023",
    x = "Population ID",
    y = "Height (cm)"
  )
```